create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "content_text" text,
    "content_html" text,
    "created_by" uuid,
    "from" character varying,
    "lastname" character varying,
    "firstname" character varying,
    "to" character varying,
    "via" character varying,
    "message_id" character varying,
    "created_at" timestamp with time zone not null default now(),
    "ticket_id" bigint
);


alter table "public"."messages" enable row level security;

create table "public"."tickets" (
    "id" bigint generated by default as identity not null,
    "subject" character varying not null,
    "assignee_id" uuid,
    "status" character varying not null default 'open'::character varying,
    "tags" character varying[],
    "is_spam" boolean,
    "last_answered_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "snoozed_at" timestamp with time zone,
    "read_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."tickets" enable row level security;

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX tickets_pkey ON public.tickets USING btree (id);

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."tickets" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."messages" add constraint "messages_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_created_by_fkey";

alter table "public"."messages" add constraint "messages_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_ticket_id_fkey";

alter table "public"."tickets" add constraint "tickets_assignee_id_fkey" FOREIGN KEY (assignee_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."tickets" validate constraint "tickets_assignee_id_fkey";

create policy "Enable read access for all users"
on "public"."messages"
as permissive
for select
to public
using (true);